### PR TITLE
Fix spelling of Ahlrichs.

### PR DESCRIPTION
**Pull request by susilehtola**

### CODE REVIEW

**Comment by wavefunction91** [comment]
This is PR looks g2g, but exposed the fact that I haven't updated the CI pipeline in awhile (GH Actions deprecated `ubuntu-18.04`). I have a fix that I've deployed elsewhere, I'll update `master` shortly and you can merge/rebase based on those changes.

**Comment by wavefunction91** [comment]
@susilehtola Please update this PR (and your other outstanding PRs) to include the recent changes in `master`

**Comment by wavefunction91** [comment]
This should be insulated from #9 (failing CI due to missing files)

**Comment by susilehtola** [comment]
> This should be insulated from #9 (failing CI due to missing files)

Whoops, looks like I pushed the testing code in the wrong branch, should work now

**Review by wavefunction91 — APPROVED** [review]

**Pull request merged**
