### PR TITLE
Refactor Source to Better Reflect Intention

### LINKED ISSUE #61: Refactor Quadrature Source to Better Reflect Intention
All quadratures seem to be on the same footing, separate into (1) priimtive quadratures (GC, GL, etc), (2) radial quadratures and (3) angular quadratures.

### PR DESCRIPTION
**Pull request by wavefunction91**
Closes #61

### CODE REVIEW

**Comment by wavefunction91** [comment]
@susilehtola I realized that I hadn't pushed a commit where I had already done that (with the exception that `angular` -> `s2` to better reflect the domain of its integration - this code is also being used in e.g. PHF where the integration is more transparantly stated over $S^2$)

**Comment by susilehtola** [comment]
What’s PHF?

**Comment by wavefunction91** [comment]
Projected HF, e.g.  https://doi.org/10.1021/acs.jctc.7b00832

**Comment by susilehtola** [comment]
> Projected HF, e.g. https://doi.org/10.1021/acs.jctc.7b00832

OK that's what I assumed, I just wasn't familiar with the use of quadrature grids in that approach

**Review by susilehtola — APPROVED** [review]

**Comment by susilehtola** [comment]
g2g on my part

**Pull request merged**
